DESCRIPTIONS = {
    "ticket_category_set": "Ticket category set to **{}**.",
    "ticket_staff_role_set": "Ticket staff role set to **{}**.",
    "ticket_transcript_channel_set": "Ticket transcript channel set to {}.",
    "ticket_panel_sent": "Ticket panel sent to {}.",
    "ticket_closed": "{} has been closed and deleted.",
    "verification_role_set": "Verification role set to {}.",
    "verification_logs_set": "Verification logs channel set to {}.",
    "verification_captcha_set": "Verification captcha set to **{}**.",
    "verification_panel": "Verification panel sent to {}.",
    "case_deleted": "You have deleted this case.",
    "moderation_logs": "Moderation logs channel set to {}.",
    "moderation_purge": "Purged `{}` messages.",
    "ticket_already_open": "You already have an open ticket at <#{}>.",
    "ticket_created": "You have created a ticket at {}.",
    "ticket_closed": "Ticket has been closed by **{}**.",
    "verification_success": "You have been verified.",
    "case_reason_edited": "You have successfully edited the reason",
    "cases_cleared": "Deleted `{}` cases.",
}